USE [master]
GO

/****** Object:  Database [BlogPostDB]    Script Date: 12/01/2025 3:05:10 p. m. ******/
CREATE DATABASE [BlogPostDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BlogPostDB.mdf', FILENAME = N'C:\Users\carlo\source\repos\WebApplication3\WebApplication3\App_Data\BlogPostDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BlogPostDB_log.ldf', FILENAME = N'C:\Users\carlo\source\repos\WebApplication3\WebApplication3\App_Data\BlogPostDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BlogPostDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BlogPostDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BlogPostDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BlogPostDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BlogPostDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BlogPostDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [BlogPostDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [BlogPostDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BlogPostDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BlogPostDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BlogPostDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BlogPostDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BlogPostDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BlogPostDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BlogPostDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BlogPostDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BlogPostDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BlogPostDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BlogPostDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BlogPostDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BlogPostDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BlogPostDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [BlogPostDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BlogPostDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BlogPostDB] SET  MULTI_USER 
GO

ALTER DATABASE [BlogPostDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BlogPostDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BlogPostDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BlogPostDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BlogPostDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BlogPostDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BlogPostDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BlogPostDB] SET  READ_WRITE 
GO


